signer: Expose digest algorithm from Signer
sethvargo/go-gcpkms pull request #6
Opened 2020-04-16 23:54 UTC by josephlr

This change does three things:
  - Exposes a `Signer.DigestAlg()` method indicating which hash algorithm _must_ be used with this key.
    - This is useful when attempting to write code that works with a user-supplied signing key
    - We are careful to only use the [`crypto.Hash`](https://golang.org/pkg/crypto/#Hash) methods that don't require the hash implementation to be linked in.
  - `Signer.Sign()` now checks that the `digest` and `ops` fields are correct
    - This is useful as the [`crypto.Signer` API](https://golang.org/pkg/crypto/#Signer) was initially created to work with private keys that could work with multiple different hash algorithms. However, this model does not apply to KMS keys.
    - Passing in incorrect parameters now fails earlier (without sending an API request) with a better error message.
    - This is similar to what we did for [TPM-based keys](https://github.com/google/go-tpm-tools/blob/4f3f3b508c7f808aec7ddbbe3ca3e1aa8276b0d6/tpm2tools/signer.go#L46-L51) (which have similar restrictions).
  - Fixes #4, so that `RSA_SIGN_PSS_4096_SHA512` works correctly.
    - This was missed in https://github.com/sethvargo/go-gcpkms/commit/a0ed38b9df1f6624c3a6ff9a4d2447d8b7beaeec, as `kmspb.CryptoKeyVersion_RSA_SIGN_PSS_4096_SHA512` was not added to the SHA512 case.

Signed-off-by: Joe Richey <joerichey@google.com>

2020-04-16 23:58 UTC, sethvargo requested changes

2020-04-16 23:58 UTC, sethvargo commented on pkg/gcpkms/signer.go
> +func (s *Signer) DigestAlg() crypto.Hash {
s/Alg/Algorithm please

2020-04-17 00:02 UTC, josephlr commented on pkg/gcpkms/signer.go
> +func (s *Signer) DigestAlg() crypto.Hash {
Fixed, good call.

2020-04-17 00:45 UTC, sethvargo approved these changes

2020-04-17 00:45 UTC, merged